### ISSUE TITLE
New thesaurus of keywords to be used for internal delwp classification of metadata records

### ISSUE THREAD

**Issue by sppigot** [geonetwork-delwp/metashare#10]
Will be supplied as a text mapping between anzlicid and keyword by Emil Skender?

**Comment by sppigot** [comment]
Vocabularies can be maintained in the Australian Research Data Commons vocab editor.

https://documentation.ands.org.au/pages/viewpage.action?pageId=19529976

**Comment by spatialgeorge** [comment]
George to request Themes / dataset list from Chris Egan

**Comment by spatialgeorge** [comment]
[sdm_category_product.xlsx](https://github.com/geonetwork-delwp/metashare/files/3195081/sdm_category_product.xlsx)

**Comment by sppigot** [comment]
Implemented and demonstrated week of May 24
