### ISSUE TITLE
Generate list of ANZLICID to UUID mappings

### ISSUE THREAD

**Issue by milleri** [geonetwork-delwp/metashare#21]
For the creation of footprints, we need METAR to generate a CSV file which lists each metashare record's anzlicid and the UUID value which is generated for GeoNetwork

**Comment by sppigot** [comment]
This can be obtained from geonetwork catalogue using utils/pyscripts/getdatabaseids.py
rastermeta and metashare tools write anzlicid to dataIdentification/citation/identifier - this gets indexed as databaseid, rastermeta tool (latest commit) also writes projectid to databaseid so the python script writes out a complete comma separated list of uuid, databaseid for all records in the catalogue.
